//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallYandexMapLocation
    {
        public int id { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
