//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSocialNetwork
    {
        public int id { get; set; }
        public string network_name { get; set; }
        public int uid_sn { get; set; }
    
        public virtual SocialNetwork SocialNetwork { get; set; }
        public virtual User User { get; set; }
    }
}
