//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSocialNetwork
    {
        public int id { get; set; }
        public string network_name { get; set; }
        public int uid_sn { get; set; }
    
        public virtual SocialNetwork SocialNetwork { get; set; }
        public virtual User User { get; set; }
    }
}
