//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportGuideEntities : DbContext
    {
        public SportGuideEntities()
            : base("name=SportGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<KindOfSport> KindOfSport { get; set; }
        public virtual DbSet<PhoneOfHall> PhoneOfHall { get; set; }
        public virtual DbSet<Workout> Workout { get; set; }
        public virtual DbSet<HallYandexMapLocation> HallYandexMapLocation { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Republic> Republic { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGender> UserGender { get; set; }
        public virtual DbSet<LoginSocialNetwork> LoginSocialNetwork { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetwork { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<HallImages> HallImages { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
    }
}
