//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportGuideEntities : DbContext
    {
        public SportGuideEntities()
            : base("name=SportGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<KindOfSport> KindOfSport { get; set; }
        public virtual DbSet<PhoneOfHall> PhoneOfHall { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Workout> Workout { get; set; }
        public virtual DbSet<HallYandexMapLocation> HallYandexMapLocation { get; set; }
    }
}
