//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public Nullable<int> city_id { get; set; }
        public string first_ip { get; set; }
        public string photo_src { get; set; }
        public bool photo_is_local { get; set; }
        public string role { get; set; }
    
        public virtual City City { get; set; }
        public virtual UserGender UserGender { get; set; }
        public virtual Login Login { get; set; }
        public virtual LoginSocialNetwork LoginSocialNetwork { get; set; }
    }
}
