//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public int id { get; set; }
        public int hall_id { get; set; }
        public int kind_of_sport_id { get; set; }
        public Nullable<int> trainer_id { get; set; }
        public int paiment_for_month { get; set; }
        public short min_age { get; set; }
        public short max_age { get; set; }
        public string info { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public bool mon { get; set; }
        public bool tue { get; set; }
        public bool wed { get; set; }
        public bool thu { get; set; }
        public bool fri { get; set; }
        public bool sat { get; set; }
        public bool sun { get; set; }
        public string gender_of_athlete { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual KindOfSport KindOfSport { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
